Progress_backend/source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from accounts.views import UserRegisterView, UserLogin, logout_view, StudentDetailView, StudentListView, CommentCreateView, SignUpUsersView
app_name = 'accounts'

urlpatterns = [
    path('login/', UserLogin.as_view(), name='log_in'),
    path('logout/', logout_view, name='log_out'),
    path('registration/', UserRegisterView.as_view(), name='user_reg'),
    path('search/', StudentListView.as_view(), name='search_student'),
    path('<int:pk>/', StudentDetailView.as_view(), name='student_detail'),
    path('<int:pk>/comment/', CommentCreateView.as_view(), name='add_comment'),
    path('sign_up/', SignUpUsersView.as_view(), name='sign_up_course'),
]

Progress_backend/source/courses/urls.py
from django.urls import path
from courses.views import IndexPageView, AboutUsView, CoursesView, LessonsView

app_name = 'courses'

urlpatterns = [
    path('', IndexPageView.as_view(), name='index'),
    path('about_us/', AboutUsView.as_view(), name='about_us'),
    path('courses/', CoursesView.as_view(), name='courses'),
    path('lessons/', LessonsView.as_view(), name='lessons')

]

Progress_backend/source/main_config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
    path('online_tests/', include('online_tests.urls')),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Progress_backend/source/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from .account_type_choices import AccoutTypeChoices
from .user_queryset import CustomUserManager
from courses import AvatarUpload
from django.contrib.auth.models import UserManager
    

class User(AbstractUser):
    avatar = models.ImageField(verbose_name='Аватар', upload_to=AvatarUpload._upload, null=True, blank=True)
    email = models.EmailField(verbose_name='Электронная почта', unique=True)
    phone = models.CharField(verbose_name='Номер телефона', max_length=20)
    role = models.CharField(verbose_name='Должность', 
                            max_length=30, 
                            choices=AccoutTypeChoices,
                            default=AccoutTypeChoices.USER
                            )
    
    object = UserManager()
    user_set = CustomUserManager()
    
    def __str__(self):
        return self.username
    
    class Meta:
        verbose_name='Пользователи'
        verbose_name_plural = 'Пользователи'


class Comment(models.Model):
    content = models.TextField(verbose_name='Содержание')
    teacher = models.ForeignKey(to=User, verbose_name='Учитель', limit_choices_to={'role': 'teacher'}, related_name='comments_given', on_delete=models.CASCADE)
    student = models.ForeignKey(to=User, verbose_name='Ученик', limit_choices_to={'role': 'user'}, related_name='comments_received', on_delete=models.CASCADE)
    created_at = models.DateTimeField(verbose_name='Время публикации', auto_now_add=True)
    
    class Meta:
        verbose_name='Комментарии'
        verbose_name_plural='Комментарии'


class SignedUpUsers(models.Model):
    first_name = models.CharField(verbose_name='Имя')
    last_name = models.CharField(verbose_name='Фамилия')
    phone = models.CharField(verbose_name='Телефон')
    email = models.EmailField(verbose_name='Электронная почта')
    course = models.CharField(verbose_name='Курс')
    
    def __str__(self) -> str:
        return f'{self.first_name}, {self.last_name}'
    
    class Meta:
        verbose_name='Заявки на курсы'
        verbose_name_plural='Заявки на курсы'

Progress_backend/source/accounts/forms.py
from django import forms
from accounts.models import Comment, User, SignedUpUsers
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import check_password


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(),
        }
        labels = {
            'content': '',
        }


class NewUserForm(UserCreationForm):
    password1 = forms.CharField(label='password',widget=forms.PasswordInput(attrs={'placeholder': 'Пароль'}))
    password2 = forms.CharField(label='password',widget=forms.PasswordInput(attrs={'placeholder': 'Повторите пароль'}))
    class Meta:
        model = User
        fields = [
            'username', 'first_name', 'last_name',
            'password1', 'password2',
            'email',
            'phone',
        ]

        widgets = {
            'username' : forms.TextInput(attrs={'placeholder': 'Логин'}),
            'first_name' : forms.TextInput(attrs={'placeholder': 'Имя'}),
            'last_name' : forms.TextInput(attrs={'placeholder': 'Фамилия'}),
            'email': forms.EmailInput(attrs={'placeholder': 'example@email.com'}),
            'phone': forms.TextInput(attrs={'placeholder': '+996 (XXX)-XXX-XXX',
                                            'type': 'text'}),
        }


class LoginUserForm(forms.Form):
    username = forms.CharField(label='username')
    password = forms.CharField(label='password', widget = forms.PasswordInput, validators=[validate_password])
           
    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = get_user_model().user_set.by_username(username)

        if not user:
            raise forms.ValidationError('User not found!')
        elif not check_password(password, user.password):
            raise forms.ValidationError('Incorrect password!')
        else:
            return self.cleaned_data


class SignedUpUsersForm(forms.Form):
    first_name = forms.CharField(label='Имя')
    last_name = forms.CharField(label='Фамилия')
    phone = forms.CharField(label='Телефон')
    email = forms.EmailField(label='Электронная почта')
    course = forms.CharField(label='Курс')

    def save(self):
        data = self.cleaned_data
        record = SignedUpUsers(first_name=data['first_name'],
                               last_name=data['last_name'],
                               phone=data['phone'],
                               email=data['email'],
                               course=data['course'])
        record.save()

Progress_backend/source/accounts/views.py
from typing import Any
from django.db.models import Q
from django.shortcuts import redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate, get_user_model
from django.views.generic import CreateView, DetailView, ListView, View
from django_filters.views import FilterView
from django.http import HttpResponseRedirect, HttpResponseBadRequest, Http404
from django.contrib.auth.mixins import UserPassesTestMixin
from django.urls import reverse
from courses.models import Visit, Course
from .models import Comment
from .json_form_handler import JsonFormHandler
from .forms import NewUserForm, LoginUserForm, CommentForm, SignedUpUsersForm
from .filters import StudentFilter

def logout_view(request):
    logout(request)
    return redirect('courses:index')


class UserLogin(View):
    def post(self, request, *args, **kwargs):
        form = LoginUserForm(request.POST)
        if form.is_valid():
            current_user = authenticate(request, 
                                    username=form['username'].value(),
                                    password=form['password'].value())
            login(request, current_user)
            return HttpResponseRedirect(self.get_success_url())
        else:
            messages.error(request, 'Неверный логин или пароль')
            return HttpResponseRedirect(self.get_success_url())
            
    def get_success_url(self):
        next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('courses:index')
        return next_url

class UserRegisterView(CreateView):
    model = get_user_model()
    template_name = 'accounts/registration.html'
    form_class = NewUserForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(reverse('courses:index'))


class StudentListView(FilterView, ListView):
    template_name = 'accounts/student_list.html'
    model = get_user_model()
    filterset_class = StudentFilter
    context_object_name = 'students'

    def get_queryset(self):
        queryset = get_user_model().objects.none()
        return queryset


class StudentDetailView(DetailView):
    model = get_user_model()
    template_name = 'accounts/student_detail.html'
    context_object_name = 'student'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.role != 'user':
            raise Http404('Страница не найдена')
        course_id = self.request.GET.get('course')
        if not course_id:
            raise Http404('Страница не найдена')
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        student_id = self.kwargs['pk']
        course_id = self.request.GET.get('course')
        student = get_object_or_404(get_user_model(), pk=student_id)
        if course_id:
            selected_course = get_object_or_404(Course, id=course_id)
            teachers = selected_course.teacher.all()
            visits = Visit.objects.all()
            visits_data = ([{'visit_date': visit.visit_date.isoformat(),
                             'is_currently_viewing': True if visit.is_currently_viewing else False,
                             'student': visit.students.id,
                             'course': visit.lesson.course.id,
                             }
                            for visit in visits])
            comments = Comment.objects.filter(student__id=student_id)
            context['filter'] = StudentFilter
            context['teachers'] = teachers
            context['selected_course'] = selected_course
            context['visits_data'] = visits_data
            context['comment_form'] = CommentForm()
            context['comments'] = comments
            context['student'] = student
        return context


class CommentCreateView(UserPassesTestMixin, CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'student_detail.html'

    def test_func(self):
        return self.request.user.role == 'teacher'

    def form_valid(self, form):
        student = get_object_or_404(get_user_model(), pk=self.kwargs.get('pk'))
        comment = form.save(commit=False)
        comment.student = student
        comment.teacher = self.request.user
        comment.save()
        course_id = self.request.GET.get('course', '')
        url = reverse('accounts:student_detail', kwargs={'pk': student.pk}) + f'?course={course_id}'
        return HttpResponseRedirect(url)


class SignUpUsersView(View):
    def post(self, request, *args, **kwargs):
        record = JsonFormHandler(request=self.request, 
                                form=SignedUpUsersForm)
        record.create_object()
        
        return record.response()

Progress_backend/source/templates/accounts/course_sign_up.html
<section id="sign-up" class="auth sign-up" hidden>
    <div class="row flex-column m-auto" id="reg_form">
        <div class="form-inputs text-center m-auto mt-5">
            <div class="form-cover" hidden></div>
            <form class="course-form">
                {% csrf_token %}   
                <h5>Отправить заявку</h5>
                <div><input id="first_name" required type="text" name="first_name" placeholder="Имя"></div>
                <div><input id="last_name" required type="text" name="last_name" placeholder="Фамилия"></div>
                <div><input id="phone" required type="text" name="phone" placeholder="+996-XXX-XXX-XXX"></div>
                <div><input id="email" required type="email" name="email" placeholder="Электронная почта"></div>
                <div>
                    <select id="course" required list="course_list" name="course" placeholder="Курс">
                        {% for course in courses %}
                            <option value="{{course.course_name}}">{{course.course_name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <button id="course_sign" type="submit" class="btn btn-warning course_sign">Подтвердить</button>
            </form>
            <div class="confirm" hidden>
                <div id="close">
                    <button class="x-mark"><i class="bi bi-x-lg"></i></button>
                </div>
                    <i class="bi bi-check2-circle"></i>
                <div class="thanks-text">
                    <span class="">Спасибо. <br> Ваша заявка отправлена</span>
                </div>
            </div>
        </div>  
    </div>
</section>
<script>
    mask('#phone')
</script>

Progress_backend/source/templates/accounts/log_in.html
{% if messages %}
    <div style="background-color: #044691; text-align: center;">
        <div style="height: 50px;
                    margin: auto;
                    background-color: #DC143C;
                    color: white;
                    font-size: 20px;
                    line-height:inherit;">
            {% for message in messages %}
                <h3 style="vertical-align: middle;">
                    {{ message }}
                </h3> 
            {% endfor %}
        </div>
    </div>
{% endif %}
<section class="auth turn-on" hidden>
    <div class="row flex-column m-auto" id="reg_form">
        <div class="form-inputs text-center m-auto mt-5">
            <form method="post" enctype="multipart/form-data" action="{% url 'accounts:log_in' %}">
                {% csrf_token %}   
                <h5>Войдите в свой аккаунт</h5>
                <span>Введите новый логин и пароль</span>
                <div><input required type="text" name="username" placeholder="Логин"></div>
                <div><input required type="password" name="password" placeholder="пароль"></div>
                <a href="{% url 'accounts:user_reg' %}"><span>Создать учетную запись</span></a>
                <button id="" type="submit" class="btn btn-warning">Подтвердить</button>
            </form>
        </div>
    </div>
</section>

Progress_backend/source/templates/accounts/registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="{% static 'js/mask/mask.js' %}"></script>
    <script src="{% static 'js/mask/mask_list.js' %}"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>
    <div class="row flex-column m-auto" id="reg_form">
        <div class="form-title text-center m-auto">
            <img src="{% static 'images/logo.png' %}" alt="">
            <h4>Образовательный центр прогресс</h4>
            <h4>Платформа организации учебного процесса</h4>
        </div>
        <div class="form-inputs text-center m-auto mt-5">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}   
                <h5>Зарегистрируйте свой аккаунт</h5>
                <span>Введите новый логин и пароль</span>
                <div>{{form.username}}</div>
                <div>{{form.first_name}}</div>
                <div>{{form.last_name}}</div>
                <div class="">{{form.password1}}</div>
                <div class="">{{form.password2}}</div>
                <div>{{form.email}}</div>
                <div>{{form.phone}}</div>
                <a href=""><span>Войти в свой аккаунт</span></a>
                <button type="submit" class="btn btn-warning">Подтвердить</button>
            </form>
        </div>
    </div>
    <style>
        body {
            background-color: #044691;
        }
        img {
            width: 400px;
        }
        h4 {
            color: white;
        }
        h5 {
            padding: 1% 10% 1% 10%;
        }
        a, span {
            color: gray;
        }
        button, input {
            width: 80%;
            border-radius: 15px;
            margin: 5% auto 10% auto;
        }
        input {
            text-align: center;
            height: 40px;
            border: 0;
            border-radius: 15px;
            background-color: rgba(255, 196, 0, 0.5);
            margin: 2% auto 2% auto;
        }
        .form-inputs {
            background-color: white;
            border-radius: 15px;
            max-width: 400px;
            
        }
        @media screen and (max-width: 772px) {
            .form-inputs {
                width: 90%;
            }
        }
        @media screen and (max-width: 401px) {
            img {
                width: 100%;
            }
        }
    </style>
    <script>
        mask('#id_phone')
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

Progress_backend/source/templates/accounts/student_detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/student_detail_styles.css' %}">
{% endblock %}
{% block content %}
<div class="detail-page">
    {% include 'partial/search_form.html' %}
    <div id="blocks-container">
        <div id="left-block">
            {% if student.avatar %}
                <img src="{{ student.avatar.url }}" alt="Аватарка">
            {% else %}
                <img src="{% static 'images/no-avatar.png' %}" alt="Аватарка">
            {% endif %}
            <h2>{{ student.first_name }} {{ student.last_name }}</h2>
            <div id="info-block">
                <div id="info-block-content">
                    <div class="info-row">
                        <p class="info-label">Курс:</p>
                        <p class="info-value">{{ selected_course.course_name }}</p>
                    </div>
                    <div class="info-row">
                        <p class="info-label">Репетитор:</p>
                        <p class="info-value">
                            {% for teacher in teachers %}
                                {{ teacher.first_name }} {{ teacher.last_name }}
                            {% endfor %}
                        </p>
                    </div>
                    <div class="info-row">
                        <p class="info-label">Тип занятия:</p>
                        <p class="info-value"></p>
                    </div>
                    <div class="info-row">
                        <p class="info-label">График занятий:</p>
                        <p class="info-value"></p>
                    </div>
                    <div class="info-row">
                        <p class="info-label">Стоимость курса:</p>
                        <p class="info-value"></p>
                    </div>
                    <div class="info-row">
                        <p class="info-label">Оплачено до:</p>
                        <p class="info-value"></p>
                    </div>
                </div>
            </div>
        </div>
        <div id="right-block">
            <div id="attendance">
                <h3>Посещаемость:</h3>
                <div id="present">
                    <p id="green">Зеленый цвет</p><img src="{% static 'images/Arrow-3.svg' %}" alt=""><p id="attendance-text">Присутствовал</p>
                </div>
                <div id="absent">
                    <p id="red">Красный цвет</p><img src="{% static 'images/Arrow-3.svg' %}" alt=""><p id="attendance-text">Отсутствовал</p>
                </div>
            </div>
            <div id="calendar"></div>
        </div>
    </div>

    <div class="feedback-section">
        <div class="feedback-content">
        <h3>Обратная связь от преподавателя</h3>
            {% if user.role == 'teacher' %}
                <div id="comment-input">
                    <form method="post" id="commentForm" action="{% url 'accounts:add_comment' pk=student.pk %}?course={{ selected_course.id }}">
                        {% csrf_token %}
                        {{ comment_form.as_p }}
                    </form>
                </div>
            {% endif %}
        </div>
        <div id="comments-container">
            {% for comment in comments %}
                <div class="comment">
                    <p>{{ comment.content }}</p>
                    <p class="comment-info">Автор: {{ comment.teacher.first_name }} {{ comment.teacher.last_name }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
{{ visits_data|json_script:"visitsData" }}
<script id="visitsData" type="application/json">
</script>
<script src="{% static 'js/calendar_script.js' %}"></script>
<div id="student-info" data-student-id="{{ student.id }}" data-course-id="{{ selected_course.id }}"></div>
{% endblock %}

Progress_backend/source/templates/accounts/student_list.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/student_list_styles.css' %}">
{% endblock %}
{% block content %}
<div class="page-container">
    {% include 'partial/search_form.html' %}
{% if filter.form.is_bound %}
    {% for student in students %}
        {% if student.avatar %}
            <img src="{{ student.avatar.url }}" alt="Аватарка" id="image">
        {% else %}
            <img src="{% static 'images/no-avatar.png' %}" alt="Аватарка" id="image">
        {% endif %}
        <h2 class="name">{{ student.first_name }} {{ student.last_name }}</h2>
        <p>Выберите курс</p>
        <div class="course-btn-container">
            {% for course in student.enrolled_courses.all %}
                <a href="{% url 'accounts:student_detail' student.pk %}?course={{ course.id }}" class="course-btn">{{ course.course_name }}</a>
            {% endfor %}
        </div>
    {% endfor %}
{% else %}
{% endif %}
</div>
{% endblock %}