Progress_backend/source/courses/urls.py
from django.urls import path
from courses.views import IndexPageView, AboutUsView, CoursesView, LessonsView

app_name = 'courses'

urlpatterns = [
    path('', IndexPageView.as_view(), name='index'),
    path('about_us/', AboutUsView.as_view(), name='about_us'),
    path('courses/', CoursesView.as_view(), name='courses'),
    path('lessons/', LessonsView.as_view(), name='lessons')

]

Progress_backend/source/main_config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
    path('online_tests/', include('online_tests.urls')),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Progress_backend/source/online_tests/urls.py
from django.urls import path

from online_tests.views import TestPassingView, TestDetailView, TestSubmitView, test_results, AllTestsView, TestView

app_name = 'online_tests'

urlpatterns = [
    path('all_tests/', AllTestsView.as_view(), name='all_tests'),
    path('start/<int:test_id>/', TestView.as_view(), name='start_test'),
    path('test/<int:test_id>/', TestPassingView.as_view(), name='take_test'),
    path('test/<int:test_id>/api/v1/', TestDetailView.as_view(), name='api_test_detail'),
    path('test/<int:test_id>/api/v1/submit', TestSubmitView.as_view(), name='api_save_user_test'),
    path('test/results/<int:user_test_id>/', test_results, name='test_results'),
]

Progress_backend/source/templates/course_tests/test_passing.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/testPassing.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
{% endblock %}
{% block title %}Test Passing{% endblock %}

{% block content %}
    <div class="container">
        <div class="test-text">
            <p>{{ test.test_name }}</p>
            <p>Количество занятий: {{ test.questions.count }}</p>
            <p>Время: {{ minutes }} минут</p>
        </div>
        <div class="time-left">
            <svg xmlns="http://www.w3.org/2000/svg" width="28px" height="28px" viewBox="0 0 24 24">
                <g>
                    <path fill="currentColor" d="M7 3H17V7.2L12 12L7 7.2V3Z">
                        <animate id="eosIconsHourglass0" fill="freeze" attributeName="opacity" begin="0;eosIconsHourglass1.end" dur="2s" from="1" to="0"></animate>
                    </path>
                    <path fill="currentColor" d="M17 21H7V16.8L12 12L17 16.8V21Z">
                        <animate fill="freeze" attributeName="opacity" begin="0;eosIconsHourglass1.end" dur="2s" from="0" to="1"></animate>
                    </path>
                    <path fill="currentColor" d="M6 2V8H6.01L6 8.01L10 12L6 16L6.01 16.01H6V22H18V16.01H17.99L18 16L14 12L18 8.01L17.99 8H18V2H6ZM16 16.5V20H8V16.5L12 12.5L16 16.5ZM12 11.5L8 7.5V4H16V7.5L12 11.5Z"></path>
                    <animateTransform id="eosIconsHourglass1" attributeName="transform" attributeType="XML" begin="eosIconsHourglass0.end" dur="0.5s" from="0 12 12" to="180 12 12" type="rotate"></animateTransform>
                </g>
            </svg>
            <p>Оставшееся время:</p>
            <div id="test-end-container" data-countdown="{{ countdown_seconds }}">
                <span id="countdown" class="countdown-style"></span>
            </div>
        </div>
        <div class="prev-next-container">
            <div class="prev-btn">
                <button type="button" class="btn1" id="prevButton">
                    <img src="{% static 'images/next.png' %}" alt="">
                </button>
                <p>Назад</p>
            </div>
            <div id="question-container" data-test-id="{{ test.id }}"></div>
            <div class="next-btn">
                <p>Вперед</p>
                <button type="button" class="btn1" id="nextButton">
                    <img src="{% static 'images/Group.png' %}" alt="">
                </button>
            </div>
        </div>
        <div class="answer-form">
            <div class="top-line"></div>
            <p>{{ test.test_name }} - бланк ответов</p>
            <div id="chekboxes-container" data-checkboxes="{{ test_id }}" class="checkboxes"></div>
            <div class="bottom-line"></div>
        </div>
        <div class="time-left-second">
            <svg xmlns="http://www.w3.org/2000/svg" width="40px" height="40px" viewBox="0 0 24 24">
                <g>
                    <path fill="currentColor" d="M7 3H17V7.2L12 12L7 7.2V3Z">
                        <animate id="eosIconsHourglass0" fill="freeze" attributeName="opacity" begin="0;eosIconsHourglass1.end" dur="2s" from="1" to="0"></animate>
                    </path>
                    <path fill="currentColor" d="M17 21H7V16.8L12 12L17 16.8V21Z">
                        <animate fill="freeze" attributeName="opacity" begin="0;eosIconsHourglass1.end" dur="2s" from="0" to="1"></animate>
                    </path>
                    <path fill="currentColor" d="M6 2V8H6.01L6 8.01L10 12L6 16L6.01 16.01H6V22H18V16.01H17.99L18 16L14 12L18 8.01L17.99 8H18V2H6ZM16 16.5V20H8V16.5L12 12.5L16 16.5ZM12 11.5L8 7.5V4H16V7.5L12 11.5Z"></path>
                    <animateTransform id="eosIconsHourglass1" attributeName="transform" attributeType="XML" begin="eosIconsHourglass0.end" dur="0.5s" from="0 12 12" to="180 12 12" type="rotate"></animateTransform>
                </g>
            </svg>
            <p>Оставшееся время:</p>
            <div id="test-end-container" data-countdown="{{ countdown_seconds }}">
                <span id="countdown2"></span>
            </div>
            {% csrf_token %}
            <div id="test-end-container" data-countdown="{{ countdown_seconds }}">
                <button class="btn2" id="submitButton">Закончить тест</button>
            </div>
        </div>
        <script src="{% static 'js/courseTestPassing.js' %}"></script>
        <script src="{% static 'js/coutdown.js' %}"></script>
    </div>
{% endblock %}


{##}
{#    Вопросы:#}
{#        questionContainer: Контейнер для каждого вопроса. Классы: col-md-6.#}
{#        questionContent: Контейнер для содержимого вопроса (текст вопроса или изображение). Классы: card-body.#}
{#        questionTitle: Заголовок вопроса. Классы: card-title.#}
{#        imageElement: Изображение вопроса (если имеется). Классы: card-img-top.#}
{#        answersList: Список ответов на вопрос. Классы: list-group, list-group-horizontal.#}
{#        answerItem: Элемент списка с ответом (текст ответа или изображение). Классы: list-group-item, flex-fill, border-0.#}
{##}
{#    Чекбоксы:#}
{#        answersContainer: Контейнер для ответов на один вопрос. Классы: d-flex, answers.#}
{#        questionNumberSpan: Элемент для отображения порядкового номера вопроса.#}
{#        checkboxContainer: Контейнер для чекбокса ответа. Классы: answer-container, custom-checkbox.#}
{#        checkbox: Чекбокс для выбора ответа. Нет примененных классов.#}
{#        imageElement: Изображение ответа (если имеется). Нет примененных классов.#}
{#        textElement: Текстовый элемент ответа. Нет примененных классов.#}
{##}
{#    Группы контейнеров:#}
{#        groupContainer: Контейнер для группы ответов на несколько вопросов. Классы: group-container.#}

Progress_backend/source/templates/course_tests/test_results.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/test_result.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="container">
        <h1>Результаты выполнения теста</h1>
        <p class="test-name">{{ test_name }}</p>
        
        {% if total_questions_count > 0 %}
            <div class="progress-bar">
                <div class="progress-bar-inner" data-progress="{{ progress }}"></div>
            </div>
        {% endif %}    
    
        <div class="result">
        <div class="correct">
            <h3>Правильно</h3>
            <p class="correct-result">{{ user_test.correct_answer_count }} из {{ total_questions_count }} (<span id="correctPercent"></span>%)</p>
        </div>
        
        <div class="incorrect">
            <h3>Неправильно</h3>
            <p class="incorrect-result">{{ user_test.incorrect_answer_cnt }} из {{ total_questions_count }} (<span id="incorrectPercent"></span>%)</p>
        </div>
        </div>    
    
        <p class="test-time">Время выполнения теста</p>
        <p class="time-spent">{{ time_spent }}</p>

        <div class="button-container">
            <a href="{% url 'courses:index' %}">На главную</a>
            <a href="{% url 'online_tests:take_test' user_test.test.id %}">Повторить тест</a>
            <a href="{% url 'online_tests:all_tests' %}">Выбрать предмет</a>
        </div>
    <div id="data-container" data-correct-answer-count="{{ user_test.correct_answer_count }}" 
         data-incorrect-answer-count="{{ user_test.incorrect_answer_cnt }}"
         data-total-questions-count="{{ total_questions_count }}">
    </div>
    </div>
    <script src="{% static 'js/progress_bar.js' %}"></script>
{% endblock %}

Progress_backend/source/templates/course_tests/test_start.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/test_start.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="test-start">
        {% if test.test_language == 'русский' %}
            <p>ТЕСТ НА РУССКОМ ЯЗЫКЕ</p>
        {% elif test.test_language == 'кыргызский' %}
            <p>ТЕСТ НА КЫРГЫЗСКОМ ЯЗЫКЕ</p>
        {% endif %}
        <p class="course-name">{{ test.test_name }}</p>
        <p class="course-description">{{ test.description }}</p>
        <a href="{% url 'online_tests:take_test' test.id %}" class="test-btn">Начать тест</a>
        <div class="time-questions">
            <ul>
                <li>Время: {{ total_minutes }} минут</li>
                <li>Количество заданий: {{ questions_count }}</li>
            </ul>
        </div>
    </div>
{% endblock %}

Progress_backend/source/templates/course_tests/tests_view.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/tests_view.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="test-view">
        <h1>ОНЛАЙН ТЕСТ</h1>
        <div class="button-container">
            <div class="button" onclick="filterTests('')" data-language="">
                <span class="button-text">Все предметы</span>
            </div>
            <div class="button" onclick="filterTests('KG')" data-language="KG">
                <span class="button-text">На кыргызском</span>
            </div>
            <div class="button" onclick="filterTests('RU')" data-language="RU">
                <span class="button-text">На русском</span>
            </div>
        </div>
        <div class="tests">
            {% for test in tests %}
                <a href="{% url 'online_tests:start_test' test.pk %}" class="test-card-link">
                    <div class="test-card">
                        <p class="test-name">{{ test.test_name }}</p>
                        <p class="test-course">
                            {% for course in test.course.all %}
                                {{ course.course_name }}
                            {% endfor %}
                        </p>
                        <div class="time-questions">
                            {% if test.test_language == 'кыргызский' %}
                                <p>Убакыт: {{ test.countdown_formatted_kg }}</p>
                                <p>Суроолордун саны: {{ test.questions.count }}</p>
                            {% else %}
                                <p>Время: {{ test.countdown_formatted_ru }}</p>
                                <p>Количество заданий: {{ test.questions.count }}</p>
                            {% endif %}
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
    <script src="{% static 'js/languageButtons.js' %}"></script>
{% endblock %}