Progress_backend/source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from accounts.views import UserRegisterView, UserLogin, logout_view, StudentDetailView, StudentListView, CommentCreateView, SignUpUsersView
app_name = 'accounts'

urlpatterns = [
    path('login/', UserLogin.as_view(), name='log_in'),
    path('logout/', logout_view, name='log_out'),
    path('registration/', UserRegisterView.as_view(), name='user_reg'),
    path('search/', StudentListView.as_view(), name='search_student'),
    path('<int:pk>/', StudentDetailView.as_view(), name='student_detail'),
    path('<int:pk>/comment/', CommentCreateView.as_view(), name='add_comment'),
    path('sign_up/', SignUpUsersView.as_view(), name='sign_up_course'),
]

Progress_backend/source/courses/urls.py
from django.urls import path
from courses.views import IndexPageView, AboutUsView, CoursesView, LessonsView

app_name = 'courses'

urlpatterns = [
    path('', IndexPageView.as_view(), name='index'),
    path('about_us/', AboutUsView.as_view(), name='about_us'),
    path('courses/', CoursesView.as_view(), name='courses'),
    path('lessons/', LessonsView.as_view(), name='lessons')

]

Progress_backend/source/main_config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
    path('online_tests/', include('online_tests.urls')),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Progress_backend/source/online_tests/urls.py
from django.urls import path

from online_tests.views import TestPassingView, TestDetailView, TestSubmitView, test_results, AllTestsView, TestView

app_name = 'online_tests'

urlpatterns = [
    path('all_tests/', AllTestsView.as_view(), name='all_tests'),
    path('start/<int:test_id>/', TestView.as_view(), name='start_test'),
    path('test/<int:test_id>/', TestPassingView.as_view(), name='take_test'),
    path('test/<int:test_id>/api/v1/', TestDetailView.as_view(), name='api_test_detail'),
    path('test/<int:test_id>/api/v1/submit', TestSubmitView.as_view(), name='api_save_user_test'),
    path('test/results/<int:user_test_id>/', test_results, name='test_results'),
]

Progress_backend/source/templates/partial/footer.html
{% load static %}
<footer>
    <div class="footer row justify-content-between">
        <div class="nav-item f-logo">
            <a class="logo-link" href="{% url 'courses:index' %}">
                <img class="image-fluid" src="{% static 'images/logo.png' %}" alt="">
            </a>
        </div>
        <div class="footer-block f-menu col-lg-2">
            <ul class="navbar-nav m-auto">
                <li class="nav-item logo">
                    <a href="">
                        <h5>Главная</h5>
                    </a>
                </li>
                <li class="nav-item"><a href="{% url 'courses:about_us' %}">О нас</a></li>
                <li class="nav-item"><a href="{% url 'courses:courses' %}">Наши курсы</a></li>
                <li class="nav-item"><a href="">Онлайн тестирование</a></li>
                <li class="nav-item"><a href="">Поиск учеников</a></li>
            </ul>
        </div>
        <div class="footer-block f-map col-lg-8 row">
            <div class="f-maps">
                <iframe id="gmap_canvas"
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13419.032130422971!2d-79.94077173022463!3d32.772154400000005!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88fe7a1ae84ff639%3A0xe5c782f71924a526!2s24%20King%20St%2C%20Charleston%2C%20SC%2029401%2C%20Amerika%20Birle%C5%9Fik%20Devletleri!5e0!3m2!1str!2str!4v1665070628853!5m2!1str!2str"
                        width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
                        referrerpolicy="no-referrer-when-downgrade">
                </iframe>
            </div>
            <div class="f-social fs-5 d-flex">
                <a href=""><i class="bi bi-instagram h-30"></i></a>
                <a href=""><i class="bi bi-telegram"></i></a>
                <a href=""><i class="bi bi-whatsapp"></i></a>
            </div>
        </div>
        <div class="footer-block f-contacts col-lg-2">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item logo">
                    <a href="">
                        <h5>Контакты</h5>
                    </a>
                </li>
                <li class="nav-item">
                    <h6>Номер телефона:</h6>
                    <a href="">+996 (505) 242 552</a>
                </li>
                <li class="nav-item">
                    <h6>E-mail:</h6>
                    <a href="">progress.kg@gmail.com</a>
                </li>
                <li class="nav-item">
                    <h6>Адрес:</h6>
                    <a href="">9-й Микрорайон, Суеркулова 10Б</a>
                </li>
            </ul>
        </div>
    </div>
</footer>

Progress_backend/source/templates/partial/header.html
{% load static %}
<header>
    <nav class="navbar navbar-expand-lg upper-panel">
        <ul class="navbar-nav d-flex">
            <li class="nav-item">
                <p class=""><i class="bi bi-geo-alt-fill nav-item"></i> 9-й Микрорайон, Суеркулова 10Б</p>
            </li>
            <li class="nav-item">
                <p class=""><i class="bi bi-phone nav-item"></i> +996 (505) 242 552</p>
            </li>
            <li class="nav-item">
                <p class=""><i class="bi bi-envelope-fill nav-item"></i> progress.kg@gmail.com</p>
            </li>
        </ul>
    </nav>
    <nav class="navbar navbar-expand-lg lower-panel">
        <div class="container-fluid">
            <div class="logo-image">
                <a href="{% url 'courses:index' %}" class="m-2">
                    <img class="nav-item logo" src="{% static 'images/logo.png' %}" alt="" width="100%">
                </a>
            </div>
            <div class="menu-button">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="bi bi-list"></i>
                </button>
            </div>
            
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-item" href="{% url 'courses:about_us' %}">О нас</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item" href="{% url 'courses:courses' %}">Наши курсы</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item" href="{% url 'online_tests:all_tests' %}">Онлайн тестирование</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item" href="{% url 'courses:lessons' %}">Видеоуроки</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item" href="{% url 'accounts:search_student' %}">Поиск учеников</a>
                    </li>
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                            <div class="logged d-flex">
                                    <span class="name_user me-5">{{ request.user.first_name }}<br>
                                        {{ request.user.last_name }}</span>
                                    
                                    <a href="{% url 'accounts:log_out' %}" id="log_out_button"
                                       class="btn btn-danger mt-0">Выход</a>
                            </div>
                        {% else %}
                            <div class="nav-item sign_in_button">
                                <button id="sign_in_button" type="button">Войти</button>
                            </div>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

Progress_backend/source/templates/partial/search_form.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/search_form.css' %}">
<form method="get" action="{% url 'accounts:search_student' %}">
    <div class="search-container">
        <p class="write-name">Напишите ФИО</p>
        {{ filter.form.as_p }}
        <button type="submit" class="search-button">ПОИСК</button>
    </div>
</form>